### PR TITLE
add a compatibility file for other POSSE-based plugins to allow addin…

### PR DESCRIPTION
**Pull request by tw2113**
…g their generated URLs into our syndication links

### CODE REVIEW

**Comment by tw2113** [comment]
See https://github.com/dshanske/syndication-links/issues/121

**Review by dshanske — CHANGES_REQUESTED** [review]
class-social-plugins.php already does what this new file does. As discussed, do not want to have two places doing the same thing. Don't mind going either way or switching to namespacing

**Comment by tw2113** [comment]
I'm good with ditching the namespace at this time and moving the add_action and callback to that plugin file, especially if it's a file meant for 3rd party compatibility. Will aim to revise the PR soon.

**Comment by dshanske** [comment]
I am fine with adopting namespaces. I no longer have to worry about 5.2 compatibility

**Comment by tw2113** [comment]
@dshanske moved it into the social plugins file and removed the originally new file.

I'm leaving it un-namespaced as that's a grander task overall.

**Pull request closed without merging**
